### ISSUE TITLE
Can't read in data on local host 

### ISSUE THREAD

**Issue by rachel662** [BodenmillerGroup/cytomapper_publication#2] opened 2021-01-01 14:48 UTC
hi there, 
I can't seem to read in the pancreas image dataset upon following the instructions and i'm not sure why, it just seems to not be able to download the dataset from the URL. Would anyone be able to help me fix this problem? the error I get is shown below.

`Error in download.file(url.cells, destfile = "data/PancreasData/CellSubset.zip") : 
  download from 'https://data.mendeley.com/public-files/datasets/cydmwsfztj/files/f1e3b8dc-56be-4172-bbc4-3a6f9de97563/file_downloaded' failed
In addition: Warning messages:
1: In download.file(url.cells, destfile = "data/PancreasData/CellSubset.zip") :
  downloaded length 277910408 != reported length 302347503
2: In download.file(url.cells, destfile = "data/PancreasData/CellSubset.zip") :
  URL 'https://md-datasets-public-files-prod.s3.eu-west-1.amazonaws.com/eb047fd4-e4b9-4c92-9f12-4c7c292ddd69': Timeout of 60 seconds was reached`

best, 
Rachel

**Comment by nilseling** [comment] 2021-01-01 15:10
Hi Rachel,

hmm, that's strange. I just tested the code on my side and it works fine. Could you please type the url `https://data.mendeley.com/public-files/datasets/cydmwsfztj/files/f1e3b8dc-56be-4172-bbc4-3a6f9de97563/file_downloaded` into your browser and see if you can manually download the cells? It could be that there was a temporary issue with Mendeleys server or an instable internet connection. 

Cheers,

Nils

**Comment by rachel662** [comment] 2021-01-01 15:37
Hi Nils, 
thanks for your help and for sharing the analysis scripts, if I manually download all the data I can read it in and use my own Rstudio. However it doesn't seem to work through the local host? 

thanks again 
Rachel

**Comment by nilseling** [comment] 2021-01-01 15:59
Hey Rachel,

are you using the docker container? I usually compiled the scripts inside the container on a linux server. But I also tested the container locally on my Mac now and I can download the data inside the container. However, it seems to be slightly slower than downloading it outside the container - so there could be a time-out kicking in if your internet connection is not stable. In any case, the analysis should be reproducible if you install the current Bioconductor release 3.12 on R 4.0 and open the `cytomapper_publication` R project.  
Best,

Nils

**Comment by rachel662** [comment] 2021-01-01 16:13
Hi Nils, 
yes, on the docker container I clicked Inspect, and then the last thing on that menu is Port, which has the local host you say to open that you can then open in your browser, I think perhaps it is the time-out that may be affecting things

I have the current Bioconductor release installed, and R version 4.0.3, if i type in the command 
`BiocManager::install("cytomapper_publication")`

I get this error 
`Bioconductor version 3.12 (BiocManager 1.30.10), R 4.0.3 (2020-10-10)
Installing package(s) 'cytomapper_publication'
Warning message:
package ‘cytomapper_publication’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages`

I don't know if there is another way to navigate to the cytomapper_publication R project? 

thanks again for your patience, I am fairly new to coding and dealing with IMC data so really appreciate the help 

Kind regards 
Rachel

**Comment by nilseling** [comment] 2021-01-01 17:13
Hey,

using `BiocManager::install` you can only install packages. I was talking about the `cytomapper_publication.Rproj` file. First, clone the repository; Second, in RStudio, simply navigate to the `cytomapper_publication.Rproj` file in the `Files` tab on the lower right hand side and click on the file. This will open the `cytomapper_publication` project and set the working directory for you. In that way you can work locally and with a stable internet connection you should be able to download the files.
Best,

Nils

**Comment by rachel662** [comment] 2021-01-01 18:59
Hey Nils, 
thanks so much, I've now cloned the repository and will see if that works! 

Best
Rachel

**Comment by nilseling** [comment] 2021-02-05 14:43
I assume that this is resolved now and will close the issue.

**Closed as completed by nilseling** 2021-02-05 14:43 UTC
